### ISSUE TITLE
CSS class .js-hidden not present in v0.23.1

### ISSUE THREAD

**Issue by woolinsilver-kainos** [alphagov/govuk_template_mustache#6]
Hi,

Latest `govuk_template_mustache` changes this:

    /* Hide for both screenreaders and browsers */
    .hidden,
    .js-enabled .js-hidden {
      display: none;
      visibility: hidden; }

to this:

    /* Hide for both screenreaders and browsers */
    .hidden {
      display: none;
      visibility: hidden; }

However, latest `govuk_frontend_toolkit` contains JavaScript which requires class `.js-hidden`.

Is this a deliberate change?

**Comment by 36degrees** [comment]
Hi Oliver,

No, this change was accidental. A new version of Template (v0.23.2) [has since been released to reintroduce the `.js-enabled .js-hidden` selector](https://github.com/alphagov/govuk_template/pull/348). Updating to this version should address any issues that you've seen.

Please re-open this issue if you continue to have issues.

Thanks,

Ollie
